<a href="https://colab.research.google.com/github/emiliomercuri/ciencia_dados/blob/main/aulas/2023_09_20_Aula_1_Python_B%C3%A1sico_(arrays%2C_listas_e_fun%C3%A7%C3%B5es).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1 - Python Básico

Nessa aula vamos ver arrays, listas e funções.

Nas células de texto você pode escrever usando a linguagem Markdown e Latex $x^2$.

$
x = \int\limits_0^\infty \sin x \, dx
$


The binomial coefficient, $\binom{n}{k}$, is defined by the expression:

$
\displaystyle \binom{n}{k} = \frac{n!}{k!(n-k)!}
$

## Bibliotecas

* numpy
* matplotlib

In [1]:
# importando bibliotecas
import numpy

In [2]:
numpy.linspace?

In [4]:
meuvetor = numpy.linspace(0,10,4)
meuvetor

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [6]:
# meuvetor = linspace(0,10,4)

## Variáveis



In [9]:
a = 5
b = 'cinco'
c = 5.0

In [11]:
type(a), type(b), type(c)

(int, str, float)

In [13]:
type(meuvetor)

numpy.ndarray

## Laços de repetição (Looping)

* for
* while

In [14]:
range?

In [20]:
# a função range(i,j,n) cria uma sequência de inteiros
# iniciando em i e terminando em j-1, com passo n. i,j,n são inteiros
# range(j) cria uma sequência de inteiros de zero (automático) até j-1
# estrutura for: para i variando no intervalor de zero a 5
for i in range(5):
  print(i)
  print("Olá! \n")
  for j in range(9,11):
    print(j)
print('Final do loop')

0
Olá! 

9
10
1
Olá! 

9
10
2
Olá! 

9
10
3
Olá! 

9
10
4
Olá! 

9
10
Final do loop


## Cortando Arrays

In [58]:
u = numpy.array([1,2,3,4,5,6.0])
u

array([1., 2., 3., 4., 5., 6.])

In [60]:
# corte do vetor do elemento 0 (inclusivo) até o elemento 3 (exclusivo)
u[0:3]

array([1., 2., 3.])

# Atribuindo variáveis arrays

In [61]:
z = u.copy()
w = u

In [62]:
z

array([1., 2., 3., 4., 5., 6.])

In [63]:
u[3] = 4.3

In [64]:
u

array([1. , 2. , 3. , 4.3, 5. , 6. ])

In [65]:
z

array([1., 2., 3., 4., 5., 6.])

In [66]:
w

array([1. , 2. , 3. , 4.3, 5. , 6. ])

# Listas e Arrays

In [67]:
# uma lista é criada usando []
a = [1, 2, 3]
a

[1, 2, 3]

In [68]:
a + a

[1, 2, 3, 1, 2, 3]

In [69]:
b = numpy.array(a)
b

array([1, 2, 3])

In [70]:
b + b

array([2, 4, 6])

In [71]:
b + 1

array([2, 3, 4])

In [73]:
numpy.sin(b)

array([0.84147098, 0.90929743, 0.14112001])

In [74]:
b**2

array([1, 4, 9])

In [76]:
a + [1]

[1, 2, 3, 1]

In [79]:
lista_generica = [1, 'al', 2.5]
lista_generica + [1]

[1, 'al', 2.5, 1]

In [82]:
a, b

([1, 2, 3], array([1, 2, 3]))

In [81]:
aa = [x + y for x,y in zip(a,a)]
aa

[2, 4, 6]

In [83]:
b + b

array([2, 4, 6])

In [87]:
timeit aa = [x + y for x,y in zip(a,a)]

769 ns ± 246 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [88]:
timeit bb = b+b

587 ns ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Definindo funções em Python

Para definir funções você vai precisar:

* nome
* eventuais parâmetros
* instruções
* retorno da função

In [91]:
def saudacao(x):
  return 'Bom dia ' + x + '. Como vai você?'

In [92]:
saudacao('Juliana')

'Bom dia Juliana. Como vai você?'

In [93]:
saudacao('Renata')

'Bom dia Renata. Como vai você?'

In [98]:
def conta(y):
  z = y + 2
  return z**2
print('teste')

teste


In [99]:
conta(1)

9