<a href="https://colab.research.google.com/github/emiliomercuri/ciencia_dados/blob/main/aulas/2023_11_01_Aula_07_Introdu%C3%A7%C3%A3o_ao_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introdução à biblioteca Pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


## Introdução aos Tensores

Tensores do Pytorch são criados usando `torch.tensor` https://pytorch.org/docs/stable/tensors.html

In [ ]:
# escalar (tensor de ordem zero)
escalar = torch.tensor(7)
escalar

tensor(7)

In [ ]:
escalar.ndim

0

In [ ]:
# Retornar o valor do tensor que nesse caso é um int
escalar.item()

7

In [ ]:
# vetor (tensor de ordem 1)
vetor = torch.tensor([7,7])
vetor

tensor([7, 7])

In [ ]:
vetor.ndim

1

In [ ]:
type(escalar), type(vetor)

(torch.Tensor, torch.Tensor)

In [ ]:
vetor.shape

torch.Size([2])

In [ ]:
escalar.shape

torch.Size([])

In [ ]:
# Matriz (tensor de ordem 2)
matriz = torch.tensor([[7,8],
                       [9,10]])
matriz

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matriz.ndim

2

In [ ]:
matriz[0]

tensor([7, 8])

In [ ]:
matriz[1]

tensor([ 9, 10])

In [ ]:
matriz.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR0 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
TENSOR0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR0.ndim

2

In [ ]:
TENSOR0.shape

torch.Size([3, 3])

In [ ]:
# Tensor
TENSOR1 = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR1.ndim

3

In [ ]:
TENSOR1.shape

torch.Size([1, 3, 3])

In [ ]:
T = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[3,3,3],
                   [4,4,6],
                   [0,0,90]]])
T

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 3,  3,  3],
         [ 4,  4,  6],
         [ 0,  0, 90]]])

In [ ]:
T.ndim

3

In [ ]:
T.shape

torch.Size([2, 3, 3])

In [ ]:
T[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
T[1]

tensor([[ 3,  3,  3],
        [ 4,  4,  6],
        [ 0,  0, 90]])

## Tensores com elementos pseudo aleatórios

Porque usar tensores aleatórios?

As redes neurais aprendem com valores iniciais aleatórios

In [ ]:
# Criar um tensor aleatório com tamanho (size) (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.8924, 0.4215, 0.4301, 0.6440],
        [0.6445, 0.5330, 0.8920, 0.8037],
        [0.9148, 0.6289, 0.4537, 0.6635]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# Criar um tensor aleatório de tamanho (224,224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.0010, 0.0613, 0.9009],
         [0.7750, 0.6126, 0.6558],
         [0.6486, 0.9456, 0.9768],
         ...,
         [0.2865, 0.5289, 0.3778],
         [0.3735, 0.9459, 0.3550],
         [0.8930, 0.6605, 0.3871]],

        [[0.5557, 0.6197, 0.0543],
         [0.1192, 0.9756, 0.5767],
         [0.0548, 0.0312, 0.2548],
         ...,
         [0.4031, 0.8940, 0.7550],
         [0.8411, 0.0731, 0.1377],
         [0.7128, 0.2186, 0.2313]],

        [[0.8813, 0.4136, 0.8571],
         [0.7477, 0.8333, 0.5260],
         [0.6259, 0.5359, 0.0155],
         ...,
         [0.5713, 0.2374, 0.3455],
         [0.6141, 0.9119, 0.4901],
         [0.2760, 0.9374, 0.7711]],

        ...,

        [[0.7869, 0.6780, 0.9793],
         [0.5457, 0.5995, 0.4642],
         [0.1308, 0.9111, 0.8137],
         ...,
         [0.0987, 0.5708, 0.6980],
         [0.1932, 0.8997, 0.2994],
         [0.6087, 0.4459, 0.6439]],

        [[0.4717, 0.8872, 0.7078],
         [0.2238, 0.4181, 0.8980],
         [0.

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
# Criar um tensor cheio de zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Criar um tensor preenchido com o número 1
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
identidade = torch.eye(3)
identidade

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Criando tensores com valores sequenciais

In [ ]:
# Usar torch.arange()

one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tensor_zero = torch.zeros_like(input=one_to_ten)
tensor_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Nota**: Tensor datatypes é um dos 3 erros mais comuns quando usamos a biblioteca PyTorch

1. Tensor não tem o datatype correto
2. Tensor não tem o formato (shape) correto
3. Tensor não está no device correto

In [ ]:
# Tensor com datatype Float32
float_32_tensor = torch.tensor([3.0143,6.09843,9.009357],
                               dtype=None, # Escolhe o datatype do tensor (float32, float16, float64...)
                               device=None, # Escolhe o processador em que o seu tensor está localizado (CPU, GPU)
                               requires_grad=False) # Escolhe se você quer que o pytorch calcule gradientes nas operações dos tensores
float_32_tensor

tensor([3.0143, 6.0984, 9.0094])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor

tensor([3.0137, 6.0977, 9.0078], dtype=torch.float16)

In [ ]:
long_tensor = float_32_tensor.type(torch.LongTensor)

In [ ]:
long_tensor

tensor([3, 6, 9])

In [ ]:
long_tensor.dtype

torch.int64

In [ ]:
long_tensor * float_32_tensor

tensor([ 9.0429, 36.5906, 81.0842])

## Obtendo informações sobre atributos dos tensores

1. Tensor não está no datatype correto: `tensor.dtype`
2. Tensor não está no formato correto: `tensor.shape`
3. Tensor não está no device correto: `tensor.device`



In [ ]:
algum_tensor = torch.rand(3,4)
algum_tensor

tensor([[0.5167, 0.4197, 0.7814, 0.9110],
        [0.2159, 0.9039, 0.1262, 0.3765],
        [0.7704, 0.2983, 0.4517, 0.6883]])

In [ ]:
algum_tensor.dtype

torch.float32

In [ ]:
algum_tensor.shape

torch.Size([3, 4])

In [ ]:
algum_tensor.size()

torch.Size([3, 4])

In [ ]:
algum_tensor.device

device(type='cpu')

# Manipulando tensores (operações de tensores)

* Adição, subtração
* Multiplicação, divisão
* Multiplicação de matriz

In [ ]:
tensor = torch.rand(2,2)
tensor.to(torch.float64)

tensor([[0.9103, 0.0117],
        [0.9883, 0.9086]], dtype=torch.float64)

In [ ]:
cuda0 = torch.device('cuda:0')
tensor_gpu = tensor.to(cuda0)
tensor_gpu

tensor([[0.9103, 0.0117],
        [0.9883, 0.9086]], device='cuda:0')

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
tensor_gpu.device

device(type='cuda', index=0)

In [ ]:
tensor_cpu = torch.rand(2,2)
tensor_cpu

tensor([[0.4117, 0.6779],
        [0.5646, 0.6842]])

In [ ]:
tensor_cpu * tensor_gpu

RuntimeError: ignored

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
torch.matmul(tensor,tensor)

tensor([[0.8403, 0.0213],
        [1.7976, 0.8371]])

In [ ]:
tensor

tensor([[0.9103, 0.0117],
        [0.9883, 0.9086]])

In [ ]:
tensor = torch.tensor([[2,2],
                       [1,1]],dtype=torch.float32)
tensor

tensor([[2., 2.],
        [1., 1.]])

In [ ]:
identidade = torch.eye(2)
identidade

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
tensor * identidade

tensor([[2., 0.],
        [0., 1.]])

In [ ]:
torch.matmul(tensor,identidade)

tensor([[2., 2.],
        [1., 1.]])

In [ ]:
tensor @ identidade

tensor([[2., 2.],
        [1., 1.]])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_C = tensor_A @ tensor_B.T
tensor_C

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.max(tensor_C)

tensor(117.)

In [ ]:
torch.argmax(tensor_C)

tensor(8)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1.0,10.0)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_novo = x.reshape(3,3)
x_novo

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x_novo.shape

torch.Size([3, 3])

In [ ]:
# Adicionar uma nova dimensão em x
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Mudar o view
x.view(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Stack = empilhar
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack = empilhar
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

# torch.squeeze

Retorna um tensor removendo uma dimensão

In [ ]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().size()

torch.Size([9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_squeezed = x_reshaped.squeeze()

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsquare
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or  dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
